# Generated by Django 5.1.5 on 2025-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_myimagemodel_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimagemodel',
            name='text',
            field=models.CharField(max_length=4192, null=True),
        ),
        migrations.AlterField(
            model_name='myimagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
