# Generated by Django 5.1.5 on 2025-02-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_myimagemodel_text_alter_myimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='myimagemodel',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
