# Generated by Django 5.1.5 on 2025-02-05 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_myimagemodel_image_alter_myimagemodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
