# Generated by Django 5.1.5 on 2025-02-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_myimagemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimagemodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
        migrations.AlterField(
            model_name='myimagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
