# Generated by Django 5.1.5 on 2025-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_myimagemodel_video_alter_myimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimagemodel',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
