# Generated by Django 5.1.5 on 2025-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_myimagemodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/icon')),
                ('headertext', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
