# Generated by Django 5.1.5 on 2025-02-05 13:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_siteinfo_headertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='headertext',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
