# Generated by Django 5.1.5 on 2025-02-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_siteinfo_headertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimagemodel',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
