# Generated by Django 5.1.5 on 2025-02-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_myimagemodel_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimagemodel',
            name='author',
            field=models.CharField(default='lud', max_length=2047),
            preserve_default=False,
        ),
    ]
