# Generated by Django 5.1.5 on 2025-02-06 10:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_myimagemodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimagemodel',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
